version: '3.9'

services:
  backend:
      container_name: backend
      build: .
      command: python manage.py run --host=0.0.0.0
      volumes:
        - .:/home/projects/BookEx
      ports:
        - "5000:5000"
      depends_on:
        - database

  database:
      container_name: database
      image: postgres:13-alpine
      restart: always
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      volumes:
        - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:


