apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  POSTGRES_PASSWORD: N3J1Q3VwaDFfbHFsZnImd29fN2VSaXN3bGh1Xy05cmE1aG94ZXRSYW1pNSo=
  SECRET_KEY: TkxiMSplWml3UklQSCsmYS1SbHNsWVVjZCAvZC9Qcm9qZWN0cy9BcHAvVDhsOE9YMzN5aQ==